version: '3.5'

services:
  server:
    build: server/
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - SERVER_PORT
      - API_HOSTNAME
      - API_PORT
      - API_DOMAIN
    depends_on:
      - api
    restart: unless-stopped
  api:
    build: api/
    hostname: ${API_HOSTNAME}
    expose:
      - '${API_PORT}'
    environment:
      - API_PORT
      - API_VERSION
      - API_AUTHENTICATION_URL
      - API_DATABASE_URL
      - API_DATABASE_NAME
      - API_DATABASE_COLLECTION
    restart: unless-stopped
