version: '3.5'

services:
  server:
    build: server/
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - SERVER_PORT
      - API_HOSTNAME
      - API_PORT
      - API_DOMAIN
      - CORE_HOSTNAME
      - CORE_PORT
      - CORE_VERSION
    networks:
      - meme
    depends_on:
      - api
    restart: unless-stopped
  api:
    build: api/
    expose:
      - '${API_PORT}'
    environment:
      - API_PORT
      - API_VERSION
      - API_CORE_URL
    networks:
      meme:
        aliases:
          - ${API_HOSTNAME}
    depends_on:
      - core
    restart: unless-stopped
  core:
    build: core/
    expose:
      - '${CORE_PORT}'
    environment:
      - CORE_PORT
      - CORE_VERSION
      - CORE_AUTHENTICATION_URL
      - CORE_DATABASE_URL
      - CORE_DATABASE_NAME
      - CORE_DATABASE_COLLECTION
    networks:
      meme:
        aliases:
          - ${CORE_HOSTNAME}
    restart: unless-stopped

networks:
  meme:
