version: '3.5'

services:
  server:
    build: server/
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - SERVER_PORT
      - API_HOSTNAME
      - API_PORT
      - API_DOMAIN
    depends_on:
      - api
    restart: unless-stopped
  api:
    build: api/
    hostname: ${API_HOSTNAME}
    expose:
      - '${API_PORT}'
    environment:
      - API_PORT
      - API_VERSION
      - API_CORE_URL
    depends_on:
      - core
    restart: unless-stopped
  core:
    build: core/
    hostname: ${CORE_HOSTNAME}
    expose:
      - '${CORE_PORT}'
    environment:
      - CORE_PORT
      - CORE_VERSION
      - CORE_AUTHENTICATION_URL
      - CORE_DATABASE_URL
      - CORE_DATABASE_NAME
      - CORE_DATABASE_COLLECTION
    restart: unless-stopped
